"""add stripe identifiers to user_subscriptions

Revision ID: 03191c652385
Revises: 10e72349f9e6
Create Date: 2026-08-02 21:53:56.057129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03191c652385'
down_revision: Union[str, None] = '10e72349f9e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('stripe_price_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_subscriptions_stripe_customer_id'), 'user_subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_stripe_subscription_id'), 'user_subscriptions', ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscriptions_stripe_subscription_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_stripe_customer_id'), table_name='user_subscriptions')
    op.drop_column('user_subscriptions', 'stripe_price_id')
    op.drop_column('user_subscriptions', 'stripe_subscription_id')
    op.drop_column('user_subscriptions', 'stripe_customer_id')
    # ### end Alembic commands ###
