"""init

Revision ID: 10e72349f9e6
Revises: 
Create Date: 2026-08-02 03:26:35.024123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e72349f9e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='Collection parameters used'),
    sa.Column('items_collected', sa.Integer(), nullable=False, comment='Number of items collected'),
    sa.Column('items_processed', sa.Integer(), nullable=False, comment='Number of items successfully processed'),
    sa.Column('items_failed', sa.Integer(), nullable=False, comment='Number of items that failed'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Collection status'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='When collection started'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='When collection completed'),
    sa.Column('duration_seconds', sa.Float(), nullable=True, comment='Collection duration in seconds'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_collections_collection_id'), 'trend_collections', ['collection_id'], unique=True)
    op.create_index(op.f('ix_trend_collections_created_at'), 'trend_collections', ['created_at'], unique=False)
    op.create_index(op.f('ix_trend_collections_id'), 'trend_collections', ['id'], unique=False)
    op.create_index(op.f('ix_trend_collections_provider'), 'trend_collections', ['provider'], unique=False)
    op.create_index(op.f('ix_trend_collections_status'), 'trend_collections', ['status'], unique=False)
    op.create_table('trend_score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.String(length=255), nullable=False, comment='Reference to trend.trend_id'),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('growth_score', sa.Float(), nullable=False),
    sa.Column('competition_score', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=True),
    sa.Column('weighted_scores', sa.JSON(), nullable=True),
    sa.Column('score_weights', sa.JSON(), nullable=True, comment='Weights used for calculation'),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_score_history_id'), 'trend_score_history', ['id'], unique=False)
    op.create_index(op.f('ix_trend_score_history_overall_score'), 'trend_score_history', ['overall_score'], unique=False)
    op.create_index(op.f('ix_trend_score_history_recorded_at'), 'trend_score_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_trend_score_history_trend_id'), 'trend_score_history', ['trend_id'], unique=False)
    op.create_table('trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.String(length=255), nullable=False, comment='Unique trend identifier'),
    sa.Column('source', sa.String(length=100), nullable=False, comment='Data source provider'),
    sa.Column('product_name', sa.String(length=255), nullable=False, comment='Product or keyword name'),
    sa.Column('brand', sa.String(length=255), nullable=True, comment='Associated brand'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Product category'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='Associated tags/keywords'),
    sa.Column('popularity_score', sa.Float(), nullable=False, comment='Popularity score (0-100)'),
    sa.Column('growth_score', sa.Float(), nullable=False, comment='Growth score (0-100)'),
    sa.Column('competition_score', sa.Float(), nullable=False, comment='Competition score (0-100)'),
    sa.Column('opportunity_score', sa.Float(), nullable=False, comment='Opportunity score (0-100)'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='Confidence score (0-100)'),
    sa.Column('overall_score', sa.Float(), nullable=False, comment='Overall weighted score (0-100)'),
    sa.Column('component_scores', sa.JSON(), nullable=True, comment='Individual component scores breakdown'),
    sa.Column('weighted_scores', sa.JSON(), nullable=True, comment='Weighted component scores'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional provider-specific data'),
    sa.Column('detected_at', sa.DateTime(), nullable=False, comment='When the trend was detected'),
    sa.Column('collected_at', sa.DateTime(), nullable=False, comment='When data was collected'),
    sa.Column('scored_at', sa.DateTime(), nullable=True, comment='When scores were calculated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether trend is active'),
    sa.Column('is_processed', sa.Boolean(), nullable=False, comment='Whether trend has been processed'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detected_at_desc', 'trends', ['detected_at'], unique=False)
    op.create_index('idx_overall_score_desc', 'trends', ['overall_score'], unique=False)
    op.create_index('idx_product_name_category', 'trends', ['product_name', 'category'], unique=False)
    op.create_index('idx_source_category', 'trends', ['source', 'category'], unique=False)
    op.create_index(op.f('ix_trends_brand'), 'trends', ['brand'], unique=False)
    op.create_index(op.f('ix_trends_category'), 'trends', ['category'], unique=False)
    op.create_index(op.f('ix_trends_created_at'), 'trends', ['created_at'], unique=False)
    op.create_index(op.f('ix_trends_detected_at'), 'trends', ['detected_at'], unique=False)
    op.create_index(op.f('ix_trends_id'), 'trends', ['id'], unique=False)
    op.create_index(op.f('ix_trends_is_active'), 'trends', ['is_active'], unique=False)
    op.create_index(op.f('ix_trends_overall_score'), 'trends', ['overall_score'], unique=False)
    op.create_index(op.f('ix_trends_product_name'), 'trends', ['product_name'], unique=False)
    op.create_index(op.f('ix_trends_source'), 'trends', ['source'], unique=False)
    op.create_index(op.f('ix_trends_trend_id'), 'trends', ['trend_id'], unique=True)
    op.create_table('product_intelligence_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.String(length=255), nullable=False, comment='Associated trend ID'),
    sa.Column('product_name', sa.String(length=255), nullable=False, comment='Product name'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Product category'),
    sa.Column('estimated_margin_score', sa.Float(), nullable=False),
    sa.Column('demand_score', sa.Float(), nullable=False),
    sa.Column('competition_score', sa.Float(), nullable=False),
    sa.Column('shipping_complexity_score', sa.Float(), nullable=False),
    sa.Column('supplier_availability_score', sa.Float(), nullable=False),
    sa.Column('seasonality_score', sa.Float(), nullable=False),
    sa.Column('impulse_buy_score', sa.Float(), nullable=False),
    sa.Column('content_potential_score', sa.Float(), nullable=False),
    sa.Column('seo_potential_score', sa.Float(), nullable=False),
    sa.Column('return_risk_score', sa.Float(), nullable=False),
    sa.Column('legal_risk_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False, comment='Overall score (0-100)'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='Confidence in analysis (0-100)'),
    sa.Column('recommendation', sa.String(length=50), nullable=False, comment='Recommendation level'),
    sa.Column('reasoning', sa.Text(), nullable=False, comment='Detailed reasoning'),
    sa.Column('strengths', sa.JSON(), nullable=False, comment='List of strengths'),
    sa.Column('weaknesses', sa.JSON(), nullable=False, comment='List of weaknesses'),
    sa.Column('rule_results', sa.JSON(), nullable=True, comment='Detailed rule results'),
    sa.Column('trend_data', sa.JSON(), nullable=True, comment='Original trend data'),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False, comment='When analysis was performed'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_category_score', 'product_intelligence_reports', ['category', 'overall_score'], unique=False)
    op.create_index('idx_product_recommendation', 'product_intelligence_reports', ['recommendation'], unique=False)
    op.create_index('idx_product_trend_id', 'product_intelligence_reports', ['trend_id'], unique=False)
    op.create_index(op.f('ix_product_intelligence_reports_category'), 'product_intelligence_reports', ['category'], unique=False)
    op.create_index(op.f('ix_product_intelligence_reports_created_at'), 'product_intelligence_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_intelligence_reports_id'), 'product_intelligence_reports', ['id'], unique=False)
    op.create_index(op.f('ix_product_intelligence_reports_overall_score'), 'product_intelligence_reports', ['overall_score'], unique=False)
    op.create_index(op.f('ix_product_intelligence_reports_product_name'), 'product_intelligence_reports', ['product_name'], unique=False)
    op.create_index(op.f('ix_product_intelligence_reports_recommendation'), 'product_intelligence_reports', ['recommendation'], unique=False)
    op.create_index(op.f('ix_product_intelligence_reports_trend_id'), 'product_intelligence_reports', ['trend_id'], unique=False)
    op.create_table('supplier_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(length=255), nullable=False, comment='Supplier ID'),
    sa.Column('product_id', sa.String(length=255), nullable=False, comment='Product ID'),
    sa.Column('cost_score', sa.Float(), nullable=False),
    sa.Column('delivery_score', sa.Float(), nullable=False),
    sa.Column('moq_score', sa.Float(), nullable=False),
    sa.Column('availability_score', sa.Float(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('flexibility_score', sa.Float(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False, comment='Overall score (0-100)'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='Confidence in evaluation (0-100)'),
    sa.Column('recommendation', sa.String(length=50), nullable=False, comment='Recommendation level'),
    sa.Column('reasoning', sa.Text(), nullable=False, comment='Detailed reasoning'),
    sa.Column('strengths', sa.JSON(), nullable=False, comment='List of strengths'),
    sa.Column('weaknesses', sa.JSON(), nullable=False, comment='List of weaknesses'),
    sa.Column('rule_results', sa.JSON(), nullable=True, comment='Detailed rule results'),
    sa.Column('rule_config', sa.JSON(), nullable=True, comment='Rule configuration used'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evaluation_recommendation', 'supplier_evaluations', ['recommendation'], unique=False)
    op.create_index('idx_evaluation_supplier_product', 'supplier_evaluations', ['supplier_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_supplier_evaluations_created_at'), 'supplier_evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_supplier_evaluations_id'), 'supplier_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_evaluations_overall_score'), 'supplier_evaluations', ['overall_score'], unique=False)
    op.create_index(op.f('ix_supplier_evaluations_product_id'), 'supplier_evaluations', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_evaluations_recommendation'), 'supplier_evaluations', ['recommendation'], unique=False)
    op.create_index(op.f('ix_supplier_evaluations_supplier_id'), 'supplier_evaluations', ['supplier_id'], unique=False)
    op.create_table('supplier_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(length=255), nullable=False, comment='Supplier ID'),
    sa.Column('product_id', sa.String(length=255), nullable=False, comment='Product ID'),
    sa.Column('unit_cost', sa.Float(), nullable=False, comment='Unit cost'),
    sa.Column('minimum_order_quantity', sa.Integer(), nullable=False, comment='Minimum order quantity'),
    sa.Column('estimated_processing_time', sa.Integer(), nullable=False, comment='Processing time in days'),
    sa.Column('estimated_shipping_time', sa.Integer(), nullable=False, comment='Shipping time in days'),
    sa.Column('available_quantity', sa.Integer(), nullable=True, comment='Available quantity'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='Currency for unit_cost'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional metadata'),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_offer_product', 'supplier_offers', ['product_id'], unique=False)
    op.create_index('idx_offer_supplier_product', 'supplier_offers', ['supplier_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_supplier_offers_id'), 'supplier_offers', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_offers_last_updated'), 'supplier_offers', ['last_updated'], unique=False)
    op.create_index(op.f('ix_supplier_offers_product_id'), 'supplier_offers', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_offers_supplier_id'), 'supplier_offers', ['supplier_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(length=255), nullable=False, comment='External supplier ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Supplier name'),
    sa.Column('source', sa.String(length=100), nullable=False, comment='Data source (api, import, etc.)'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='Supplier country'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='Preferred currency'),
    sa.Column('contact', sa.JSON(), nullable=True, comment='Contact information'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional metadata'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_supplier_country', 'suppliers', ['country'], unique=False)
    op.create_index('idx_supplier_source', 'suppliers', ['source'], unique=False)
    op.create_index(op.f('ix_suppliers_created_at'), 'suppliers', ['created_at'], unique=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=True)
    op.create_table('brand_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False, comment='Associated product ID'),
    sa.Column('supplier_id', sa.String(length=255), nullable=True, comment='Associated supplier ID'),
    sa.Column('brand_name', sa.String(length=255), nullable=False, comment='Brand name'),
    sa.Column('slogan', sa.String(length=500), nullable=True, comment='Brand slogan'),
    sa.Column('mission', sa.Text(), nullable=True, comment='Brand mission'),
    sa.Column('vision', sa.Text(), nullable=True, comment='Brand vision'),
    sa.Column('target_audience', sa.String(length=255), nullable=True, comment='Target audience segment'),
    sa.Column('customer_persona', sa.JSON(), nullable=True, comment='Detailed customer persona'),
    sa.Column('tone_of_voice', sa.String(length=255), nullable=True, comment='Primary tone of voice'),
    sa.Column('writing_style', sa.JSON(), nullable=True, comment='Writing style guidelines'),
    sa.Column('color_palette', sa.JSON(), nullable=True, comment='Color palette with hex codes'),
    sa.Column('typography', sa.JSON(), nullable=True, comment='Typography recommendations'),
    sa.Column('logo_prompt', sa.Text(), nullable=True, comment='Logo design prompt'),
    sa.Column('packaging_prompt', sa.Text(), nullable=True, comment='Packaging design prompt'),
    sa.Column('product_photography_prompt', sa.Text(), nullable=True, comment='Product photography prompt'),
    sa.Column('hero_banner_prompt', sa.Text(), nullable=True, comment='Hero banner prompt'),
    sa.Column('social_media_style', sa.Text(), nullable=True, comment='Social media style guidelines'),
    sa.Column('seo_style', sa.Text(), nullable=True, comment='SEO writing style'),
    sa.Column('email_style', sa.Text(), nullable=True, comment='Email writing style'),
    sa.Column('trust_elements', sa.JSON(), nullable=True, comment='Trust-building elements'),
    sa.Column('unique_value_proposition', sa.JSON(), nullable=True, comment='Unique value proposition'),
    sa.Column('differentiators', sa.JSON(), nullable=True, comment='Competitive differentiators'),
    sa.Column('domain_name_suggestions', sa.JSON(), nullable=True, comment='Domain name suggestions'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='Overall confidence score'),
    sa.Column('validation_result', sa.JSON(), nullable=True, comment='Validation results'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional metadata'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brand_name', 'brand_profiles', ['brand_name'], unique=False)
    op.create_index('idx_brand_product_supplier', 'brand_profiles', ['product_id', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_brand_profiles_brand_name'), 'brand_profiles', ['brand_name'], unique=False)
    op.create_index(op.f('ix_brand_profiles_created_at'), 'brand_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_brand_profiles_id'), 'brand_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_brand_profiles_product_id'), 'brand_profiles', ['product_id'], unique=False)
    op.create_index(op.f('ix_brand_profiles_supplier_id'), 'brand_profiles', ['supplier_id'], unique=False)
    op.create_table('store_blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Owner user ID'),
    sa.Column('brand_profile_id', sa.String(length=255), nullable=False, comment='Brand profile ID'),
    sa.Column('product_id', sa.String(length=255), nullable=False, comment='Product ID'),
    sa.Column('supplier_id', sa.String(length=255), nullable=True, comment='Supplier ID'),
    sa.Column('store_name', sa.String(length=255), nullable=False, comment='Store name'),
    sa.Column('store_description', sa.Text(), nullable=False, comment='Store description'),
    sa.Column('tagline', sa.String(length=500), nullable=True, comment='Store tagline'),
    sa.Column('blueprint_json', sa.JSON(), nullable=False, comment='Complete store blueprint'),
    sa.Column('validation_score', sa.Float(), nullable=False, comment='Overall validation score'),
    sa.Column('validation_result', sa.JSON(), nullable=True, comment='Validation results'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional metadata'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_store_brand_product', 'store_blueprints', ['brand_profile_id', 'product_id'], unique=False)
    op.create_index('idx_store_name', 'store_blueprints', ['store_name'], unique=False)
    op.create_index(op.f('ix_store_blueprints_brand_profile_id'), 'store_blueprints', ['brand_profile_id'], unique=False)
    op.create_index(op.f('ix_store_blueprints_created_at'), 'store_blueprints', ['created_at'], unique=False)
    op.create_index(op.f('ix_store_blueprints_id'), 'store_blueprints', ['id'], unique=False)
    op.create_index(op.f('ix_store_blueprints_product_id'), 'store_blueprints', ['product_id'], unique=False)
    op.create_index(op.f('ix_store_blueprints_store_name'), 'store_blueprints', ['store_name'], unique=False)
    op.create_index(op.f('ix_store_blueprints_supplier_id'), 'store_blueprints', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_store_blueprints_user_id'), 'store_blueprints', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_store_blueprints_user_id'), table_name='store_blueprints')
    op.drop_index(op.f('ix_store_blueprints_supplier_id'), table_name='store_blueprints')
    op.drop_index(op.f('ix_store_blueprints_store_name'), table_name='store_blueprints')
    op.drop_index(op.f('ix_store_blueprints_product_id'), table_name='store_blueprints')
    op.drop_index(op.f('ix_store_blueprints_id'), table_name='store_blueprints')
    op.drop_index(op.f('ix_store_blueprints_created_at'), table_name='store_blueprints')
    op.drop_index(op.f('ix_store_blueprints_brand_profile_id'), table_name='store_blueprints')
    op.drop_index('idx_store_name', table_name='store_blueprints')
    op.drop_index('idx_store_brand_product', table_name='store_blueprints')
    op.drop_table('store_blueprints')
    op.drop_index(op.f('ix_brand_profiles_supplier_id'), table_name='brand_profiles')
    op.drop_index(op.f('ix_brand_profiles_product_id'), table_name='brand_profiles')
    op.drop_index(op.f('ix_brand_profiles_id'), table_name='brand_profiles')
    op.drop_index(op.f('ix_brand_profiles_created_at'), table_name='brand_profiles')
    op.drop_index(op.f('ix_brand_profiles_brand_name'), table_name='brand_profiles')
    op.drop_index('idx_brand_product_supplier', table_name='brand_profiles')
    op.drop_index('idx_brand_name', table_name='brand_profiles')
    op.drop_table('brand_profiles')
    op.drop_index(op.f('ix_suppliers_supplier_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_created_at'), table_name='suppliers')
    op.drop_index('idx_supplier_source', table_name='suppliers')
    op.drop_index('idx_supplier_country', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_supplier_offers_supplier_id'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_product_id'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_last_updated'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_id'), table_name='supplier_offers')
    op.drop_index('idx_offer_supplier_product', table_name='supplier_offers')
    op.drop_index('idx_offer_product', table_name='supplier_offers')
    op.drop_table('supplier_offers')
    op.drop_index(op.f('ix_supplier_evaluations_supplier_id'), table_name='supplier_evaluations')
    op.drop_index(op.f('ix_supplier_evaluations_recommendation'), table_name='supplier_evaluations')
    op.drop_index(op.f('ix_supplier_evaluations_product_id'), table_name='supplier_evaluations')
    op.drop_index(op.f('ix_supplier_evaluations_overall_score'), table_name='supplier_evaluations')
    op.drop_index(op.f('ix_supplier_evaluations_id'), table_name='supplier_evaluations')
    op.drop_index(op.f('ix_supplier_evaluations_created_at'), table_name='supplier_evaluations')
    op.drop_index('idx_evaluation_supplier_product', table_name='supplier_evaluations')
    op.drop_index('idx_evaluation_recommendation', table_name='supplier_evaluations')
    op.drop_table('supplier_evaluations')
    op.drop_index(op.f('ix_product_intelligence_reports_trend_id'), table_name='product_intelligence_reports')
    op.drop_index(op.f('ix_product_intelligence_reports_recommendation'), table_name='product_intelligence_reports')
    op.drop_index(op.f('ix_product_intelligence_reports_product_name'), table_name='product_intelligence_reports')
    op.drop_index(op.f('ix_product_intelligence_reports_overall_score'), table_name='product_intelligence_reports')
    op.drop_index(op.f('ix_product_intelligence_reports_id'), table_name='product_intelligence_reports')
    op.drop_index(op.f('ix_product_intelligence_reports_created_at'), table_name='product_intelligence_reports')
    op.drop_index(op.f('ix_product_intelligence_reports_category'), table_name='product_intelligence_reports')
    op.drop_index('idx_product_trend_id', table_name='product_intelligence_reports')
    op.drop_index('idx_product_recommendation', table_name='product_intelligence_reports')
    op.drop_index('idx_product_category_score', table_name='product_intelligence_reports')
    op.drop_table('product_intelligence_reports')
    op.drop_index(op.f('ix_trends_trend_id'), table_name='trends')
    op.drop_index(op.f('ix_trends_source'), table_name='trends')
    op.drop_index(op.f('ix_trends_product_name'), table_name='trends')
    op.drop_index(op.f('ix_trends_overall_score'), table_name='trends')
    op.drop_index(op.f('ix_trends_is_active'), table_name='trends')
    op.drop_index(op.f('ix_trends_id'), table_name='trends')
    op.drop_index(op.f('ix_trends_detected_at'), table_name='trends')
    op.drop_index(op.f('ix_trends_created_at'), table_name='trends')
    op.drop_index(op.f('ix_trends_category'), table_name='trends')
    op.drop_index(op.f('ix_trends_brand'), table_name='trends')
    op.drop_index('idx_source_category', table_name='trends')
    op.drop_index('idx_product_name_category', table_name='trends')
    op.drop_index('idx_overall_score_desc', table_name='trends')
    op.drop_index('idx_detected_at_desc', table_name='trends')
    op.drop_table('trends')
    op.drop_index(op.f('ix_trend_score_history_trend_id'), table_name='trend_score_history')
    op.drop_index(op.f('ix_trend_score_history_recorded_at'), table_name='trend_score_history')
    op.drop_index(op.f('ix_trend_score_history_overall_score'), table_name='trend_score_history')
    op.drop_index(op.f('ix_trend_score_history_id'), table_name='trend_score_history')
    op.drop_table('trend_score_history')
    op.drop_index(op.f('ix_trend_collections_status'), table_name='trend_collections')
    op.drop_index(op.f('ix_trend_collections_provider'), table_name='trend_collections')
    op.drop_index(op.f('ix_trend_collections_id'), table_name='trend_collections')
    op.drop_index(op.f('ix_trend_collections_created_at'), table_name='trend_collections')
    op.drop_index(op.f('ix_trend_collections_collection_id'), table_name='trend_collections')
    op.drop_table('trend_collections')
    # ### end Alembic commands ###
